### ISSUE TITLE
Request id inaccessible

### ISSUE THREAD

**Issue by brotherbain** [onelogin/python-saml#106]
I noticed that you're able to hand a request id over to process_response.  After scouring the code, it seems to me that that request id is not actually accessible.  The id seems to be generated by a temporary authn_request object which is discarded after creating the redirect url.  If it isn't saved anywhere, how can it ever be used without decoding the url again before sending?  Did I miss something?

**Comment by pitbulk** [comment]
Hi @brotherbain,

You are right, most of the Service Provider deployed will allow IdP- initiaited SSO so don't care about the AuthNRequest ID.

The toolkit provide the login method at Auth class that generates the AuthNRequest and you are right if you use that, you can't get the ID in an easy way.

Instead, use the login method, you can use something like:
```
        settings = auth.get_settings()

        authn_request = OneLogin_Saml2_Authn_Request(settings, force_authn, is_passive)

        saml_request = authn_request.get_request()
        authn_request_id = authn_request.get_id()
        parameters = {'SAMLRequest': saml_request}

        if return_to is not None:
            parameters['RelayState'] = return_to
        else:
            parameters['RelayState'] = OneLogin_Saml2_Utils.get_self_url_no_query(auth.__request_data)

        security = settings.get_security_data()
        if security.get('authnRequestsSigned', False):
            parameters['SigAlg'] = security['signatureAlgorithm']
            parameters['Signature'] = auth.build_request_signature(saml_request, parameters['RelayState'], security['signatureAlgorithm'])
        return auth.redirect_to(auth.get_sso_url(), parameters)
```
 I wanted to avoid more complexity on the login method, that means not 100% of the cases covered with a hight level method, but you can always use the functionalities that the toolkit provides.

**Comment by brotherbain** [comment]
I think simply saving the request id to a self.__request_id in similar fashion to other variables that may need to be referenced outside the class would work just fine.  you wouldn't have to change login's interface, and then you have a way to make use of that great request_id validator that's currently collecting dust in the process_response method.  Security is key to all authentication, and that little check goes a long way toward preventing replay attacks on this otherwise-exceptional library.  What do you think?

**Comment by brotherbain** [comment]
oops!  after a second look, it really looks like it should be the authentication request that is saved to self.__auth_request with an accessor.  then you could:
```
saml_auth = OneLogin_Saml2_Auth(req, settings)
response = saml_auth.login()
session['saml_request_id'] = saml_auth.get_auth_request().get_id()
return redirect(response)
```

**Comment by pitbulk** [comment]
The self.__request_id solution does not solve the problem since you need to store the ID value and the login and logout method executes a redirection when called.

So I need to extend login and logout methods to support the "stay" parameter that determines if the redirection is done or not.

**Comment by brotherbain** [comment]
So far as I can tell, they merely create a url for redirection, but that can url can be withheld until the system is ready to return it.  the rest can be up to the user.  it's far better, I'd say, than having a parameter in your process_request method that is unusable.  I agree that perhaps it isn't ideal either.  Just throwing out ideas :smile:

**Comment by pitbulk** [comment]
At the [python toolkit](https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L44) and [ruby-saml](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L16), the redirection is executed by the python framework instead of the toolkit, the SSO/SLO url + samlrequest is returned by the login/logout method.

At the php toolkit and at the [java-saml toolkit](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/Auth.java#L200). the redirection is executed.

I think I will implement an "stay" option at java-saml and php-saml and let developers retrieve the request ID as you asked for. But I dislike to save the request object on the auth object.

The alternative as you also suggested is the get_request_id() saving previously the id at the auth object when login/logout executed, but I dislike the fact that this object only belong the requests and only available after execute the login/logout method.

**Comment by brotherbain** [comment]
I agree it does feel a bit clunky.  hmmm... I'll be thinking about this a bit more, then.  a better answer may yet reveal itself.  Thanks for hearing me out!
