### ISSUE TITLE
sp_validation_only flag not passed into the OneLogin_Saml2_Settings constructor

### ISSUE THREAD

**Issue by jimmyislive** [onelogin/python-saml#121]
I would like to create a OneLogin_Saml2_Auth object but be able to add a keyword param called sp_validation_only=True. THis should be passed into the OneLogin_Saml2_Settings constructor while creating the embedded OneLogin_Saml2_Settings object.

I would like to create such an auth object in places where I only need SP details. e.g. I am verifying a response from an IdP.

**Comment by pitbulk** [comment]
Review the use of sp_validation_only at the metadata view:
https://github.com/onelogin/python-saml/blob/185ebbd177cc603f95abfef9a39e57baf637cb82/demo-django/demo/views.py#L121

You may be able to do something similar for the SAMLResponse, using that class directly rather than use OneLogin_Saml2_Auth
