### ISSUE TITLE
python-saml

### ISSUE THREAD

**Issue by mabahma** [onelogin/python-saml#186]
Hello

Is the python-saml usable to connect any python application to and IDP via SAML ?

I'm looking to connect odoo to shiboleth IDP..

Possible , or have i tu use OneLogin IDP?

if yes how should i do it ?

**Comment by pitbulk** [comment]
You can use it to connect with any Identity Provider.

Are you creating a Odoo SAML plugin?

**Comment by mabahma** [comment]
Thank you for your answer..
I'm only trying to connect odoo to our Identity and access management system which support SAML.

I've tried this module of odoo : https://github.com/xcgd/auth_saml but i didn't get it to work ( it is based on lasso  : http://lasso.entrouvert.org/download/)..

This is why i was looking if there were any other simple alternatives..

So ..i've read the documentation, and if my undertanding is good, i should copy saml folder into odoo (where? ) and configure the files , and i will be done ? it is that that simple? 

Thank you a lot

**Comment by pitbulk** [comment]
Not that simple, you will need to create a new plugin like the [one published](https://github.com/xcgd/auth_saml), but the new one will use python-saml to take care of all the SAML part instead of lasso.

Probably around 10-15h of work if you understand how SAML works, how python-saml works and have an idea about odoo authentication plugins...

**Comment by mabahma** [comment]
Thank you a lot.

**Comment by pitbulk** [comment]
any progress on that?
