### ISSUE TITLE
Strange Behaviour using ADFS as an idp

### ISSUE THREAD

**Issue by pdomineaux** [onelogin/python-saml#187]
Hello,
Thanks for the auth plugin.

I've configured my local taiga instance to use the [taiga-contrib-saml-auth](https://github.com/jgiannuzzi/taiga-contrib-saml-auth) to authenticate my users against an ADFS and it works fine if I use the external access.
If I try to authenticate on the local network, there is an error : 

Activity ID: 00000000-0000-0000-3806-0080010000d2
Error time: Tue, 21 Mar 2017 15:37:41 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Nothing on the taiga logs neither on ADFS.
Do you have any idea to solve my problem?

**Comment by pitbulk** [comment]
Use [SAMLTracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) plugin to record the SAML traffic between IdP and SP.

I guess that the SAML IdP when you are in the local network instead of a SAMLResponse with status=Success is sending a status=Responder, and the python-saml toolkit reject it and does not log the user.

I'm not an ADFS expert but I think is something related with its settings.

btw, I'm sure that something should appear on ADFS logs.

**Comment by pdomineaux** [comment]
Hello,

thank you for the quick reply.
But even with the ADFS in debug mode I can't see any log related to the SP taiga.
I've recorded the saml exchange using SAML Tracer but I don't know if I can securely post the content on this post?

**Comment by pitbulk** [comment]
You can send it to my mail

**Comment by pdomineaux** [comment]
Ok, 

so when I use : 

urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
instead of :
urn:oasis:names:tc:SAML:2.0:nameid-format:transient
as described in the documentation of python-saml/taiga-contrib-saml-auth

It works for most of my clients but not for some others:
- typically It was working on my iPad inside the network, but not now and it works now on the iPad of my colleague 
and both iPads are on the same network


I can not figure out what's going on.
