### ISSUE TITLE
Allow using different classes to build the request

### ISSUE THREAD

**Issue by pgcd** [onelogin/python-saml#215]
I need to connect to an Identity Provider that requires the Issuer to have a specific value (not my SP's entityId that I use in the metadata). 
The most straightforward way of doing so would be subclassing OneLogin_Saml2_Authn_Request and overriding the relevant method so that I can use a different template and pass some extra values to the request, but as far as I can tell there's no support for such an approach.
Of course, if there are alternative ways to reach the same goal, that'd be great too.

**Comment by pitbulk** [comment]
Sorry but the value of the Issuer must be the SP's entityId , this is what SAML standard says.

If you "hack" the code and send a different value.. then, what happens when the IdP sends the SAMLResponse with SAML Audience restriction value equal to the value sent on the AuthNRequest?
Will you also modify that part? Then.. why just not change SP's entityId to the value that IdP expects?

**Comment by pgcd** [comment]
I will check with them but, so far, what has been requested is a numeric ID as issuer, instead of the URL we have as entityId and which I gave the provider (they sent me the numeric ID afterwards, and accepted the entityId without complaint).
The main problem here is that this provider is extremely large and there are thousands of SPs working with them who received the same instruction I received, which leads me to think that their instructions *can* be followed to the letter, and that there's something wrong with my current setup/implementation, rather than with their instructions.
