### ISSUE TITLE
AWS SSO - Invalid SAML Response

### ISSUE THREAD

**Issue by gohackfelipe** [onelogin/python-saml#259]
Hi all,

I'm trying to integrate the demo-flask application with AWS SSO.

At end of request, I've received the follow error:

`Element '{urn:oasis:names:tc:SAML:2.0:assertion}AttributeStatement': Missing child element(s). Expected is one of ( {urn:oasis:names:tc:SAML:2.0:assertion}Attribute, {urn:oasis:names:tc:SAML:2.0:assertion}EncryptedAttribute ).
Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd`

Anyone knows how to start resolving this? :(

**Comment by pitbulk** [comment]
The SAMLResponse you received contains an AttributeStatement element that does not contain Attribute or EncryptedAttribute. The [SAML spec ](http://www.datypic.com/sc/saml2/e-saml_AttributeStatement.html) requires at least 1, but none provided.

You may configure the Identity Provider properly in order to retrieve some attribute.
