### ISSUE TITLE
singleLogoutService setting for SP not used?

### ISSUE THREAD

**Issue by ekallevig** [onelogin/python-saml#42]
New to SAML here so excuse my ignorance if this is a dumb question.

In the settings.json file under the `sp` section, you can set urls for `assertionConsumerService` and `singleLogoutService`.

In the login request, the `assertionConsumerService` is sent to the IDP via the `AssertionConsumerServiceURL` attribute and the IDP then uses that url to post the login response assertion. That works great for login.

For logout, however I don't see the SP's `singleLogoutService` value being sent to the IDP at all (I looked in the python-saml code and I only see the `singleLogoutService` value for the **IDP** being referenced).   My assumption is that I can specify a url in the logout request where the IDP should post a logout response similar to how I specify where it should post the login response.

Currently, the IDP is posting to the url I originally set up in the metadata file I sent to the IDP manager. I assumed I could override that location in the logout request the same way I override the `AssertionConsumerServiceURL` in the login request.

Am I misunderstanding how this should work?  Do I need to have something enabled on the IDP to make this work?

**Comment by pitbulk** [comment]
In SAML, the IdP an the SP entities exchange metadata (in order to set the circle of trust), So each entity knows the endpoints of the other involved entities.

Related to the "AssertionConsumerServiceURL" issue, the AuthnRequest sent by the SP to the IdP is referenced in the AssertionConsumerServiceURL value (as you noted). But notice that this value is optional. IdP must know the SP ACS endpoint (The IdP MUST ensure that the value specified is in fact associated with the SP, for example with the metadata exchanged)
Reading the SAML protocol documentation I don't see that a LogoutRequest can define the Single Logout Service endpoint in the way that you expected.

Why you want to override the endpoint location by the data of the request instead of have the correct metadata updated?

**Comment by ekallevig** [comment]
@pitbulk I wanted to override for convenience during local development, but if that's not how it's generally supposed to work, then that's fine.  Here's what I'm not understanding:

1. If you aren't supposed to override the callback location via request, why is the `AssertionConsumerServiceURL` attribute even sent in the request?  Is it just an additional way of verifying with the IDP that the request is actually coming from the SP?

2. If you aren't supposed to override the callback location, then why is that override actually working for me during login (ie. the `AssertionConsumerServiceURL` value I'm sending in the request is being used by the IDP instead of the stored metadata value)? Does that just mean the IDP is mis-configured?  ie. Is it not supposed to work that way?

**Comment by pitbulk** [comment]
I don't wrote the SAML protocol so don't know what the authors thought.

I can say that you can trust the AssertionConsumerServiceURL of an AuthnRequest if is signed, otherwise you can't trust it if it is different that the once registered as the metadata of the SP.   (An attacker can make than an IdP returns a SAML Response to an endpoint that he controls with user data).
