### ISSUE TITLE
How do I integrate this with multiple IDPs?

### ISSUE THREAD

**Issue by diwu1989** [onelogin/python-saml#64]
How can I use this to securely integrate with multiple customer's IDP's?

It looks like it is hard coded against a single IDP.

**Comment by pitbulk** [comment]
Issue duplicated: #52 

The toolkit was not initially designed to be used with multiple IdPs, instead with the OneLogin IdP, but you can with a little effort support multiple IdPs.

In the toolkit you will see 2 demos (django, flask) that uses a settings.js file that contain a json object.

In order to support multiple IdPs you can store each IdP-SP data on different files or store different json objects on a database.
