### ISSUE TITLE
ADFS support

### ISSUE THREAD

**Issue by gsvitak** [onelogin/python-saml#92]
Hello, 

Can I use python-saml to build a SP against an ADFS endpoint? If yes, can you please specify which versions of ADFS and which modes/profiles (ie active/passive and http-redirect/forms auth etc)

**Comment by pitbulk** [comment]
Yes, python-saml can be used to be connected with ADFS 2.0 and ADFS 3.0.

All messages are sent and expects to be received using the HTTP-Redirect binding, except the SAMLResponse sent from the IdP using the HTTP-POST binding.

Review the [settings section](https://github.com/onelogin/python-saml#settings) in order to learn how configure the python-saml. 

The passive/active can be set adding [an specific parameter to the login method](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L260).

Review the demos to learn how it works, for example, take a look to the [django-demo](https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L31)

**Comment by gsvitak** [comment]
GREAT!! thanks for the quick response.
